server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /var/lib/promtail/positions.yaml

clients:
  - url: ${LOKI_PUSH_URL}

scrape_configs:
  - job_name: synology-gitea
    docker_sd_configs:
      - host: unix:///var/run/docker.sock
        refresh_interval: 15s
        filters:
          - name: label
            values: ["com.docker.compose.service=gitea"]
    relabel_configs:
      - source_labels: ["__meta_docker_container_name"]
        regex: "/gitea"
        action: keep
      - source_labels: ["__meta_docker_container_name"]
        regex: "/(.*)"
        target_label: container
      - target_label: host
        replacement: ${PROMTAIL_HOST_LABEL}
      - target_label: job
        replacement: synology-gitea
    pipeline_stages:
      - docker: {}
