services:
  wireguard:
    image: masipcat/wireguard-go:latest
    container_name: hhnas4-wireguard
    restart: unless-stopped
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun
    volumes:
      - ./wg0.conf:/etc/wireguard/wg0.conf:ro
    sysctls:
      - net.ipv4.conf.all.forwarding=1
    command: wg0
