services:
  wireguard:
    image: masipcat/wireguard-go:latest
    container_name: nas-host-wireguard
    restart: unless-stopped
    cap_add:
      - NET_ADMIN
    volumes:
      - ./wg0.conf:/etc/wireguard/wg0.conf:ro
    sysctls:
      - net.ipv4.conf.all.forwarding=1
