services:
  wireguard:
    image: masipcat/wireguard-go@sha256:696206e5954d3bdeaa59d5a006dc8de7d9ccdbe1fb0ac1b41650ea75cbd133e9
    container_name: nas-host-wireguard
    restart: unless-stopped
    cap_add:
      - NET_ADMIN
    volumes:
      - ./wg0.conf:/etc/wireguard/wg0.conf:ro
    sysctls:
      - net.ipv4.conf.all.forwarding=1
